//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digital_Diary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Ddiary
    {
        public int Id { get; set; }
        
        [DisplayName("Write your today story")]
        public string Written { get; set; }
        [DisplayName("Upload Image")]
        public string imagePath { get; set; }
        public string Date { get; set; }
        public string ModifiedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public int R_Id { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
