//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digital_Diary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Login
    {
        public int Id { get; set; }
        [DisplayName("Enter Username :")]
        public string userName { get; set; }
        [DisplayName("Enter Password :")]
        public string Password { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
