//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digital_Diary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Registration
    {
        // internal readonly object ImageFile;
        
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Location { get; set; }
        [DisplayName("Upload Your Picture")]
        public string image { get; set; }
        public string userName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Status { get; set; }
        public string diaryName { get; set; }
        public string date {get ;   set ;  }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
